on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string

jobs:
  resolve-modules:
    uses: ./.github/workflows/resolve-modules.yml

  build-and-test:
    needs: resolve-modules
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.resolve-modules.outputs.modules) }}
    defaults:
      run:
        working-directory: ${{ matrix.module }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - run: go build -v ./...
      - run: go test  -v ./...

  generate:
    needs: resolve-modules
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.resolve-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - shell: bash
        working-directory: ${{ matrix.module }}
        # TODO: should we limit git status to just the working directory?
        # Also, should we run git status beforehand to check for changes?
        run: |
          set -x
          go generate -v ./...
          git status --porcelain | tee /dev/full

  lint:
    needs: resolve-modules
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.resolve-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix.module }}
