on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string

jobs:
  resolve-modules:
    # TODO: it would be better to use the relative path to resolve-modules.yml
    # here but it doesn't work with act (yet -- nektos/act#1875).
    uses: avamsi/go-nogo/.github/workflows/resolve-modules.yml@main

  lint:
    needs: resolve-modules
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.resolve-modules.outputs.modules) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ${{ matrix.module }}
          # TODO: consider enabling revive too.
          args: --enable=gofumpt,gosec,misspell,prealloc

  generate:
    needs: resolve-modules
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.resolve-modules.outputs.modules) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - working-directory: ${{ matrix.module }}
        run: |
          set -x
          go generate -v ./...
          git diff HEAD | tee /dev/full

  mod-tidy:
    needs: resolve-modules
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.resolve-modules.outputs.modules) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - working-directory: ${{ matrix.module }}
        run: |
          set -x
          go mod tidy
          git diff HEAD | tee /dev/full

  build-and-test:
    needs: resolve-modules
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.resolve-modules.outputs.modules) }}
      fail-fast: false
    defaults:
      run:
        working-directory: ${{ matrix.module }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go build -v ./...
      - run: go test  -v ./...
      # Test with -race and -count=10000 if both build and (vanilla) test are
      # successful, but it's probably overkill to run them on every commit, so
      # run them an order of magnitude less often using metadata.
      - run: ': ${{ github.event.number }} ${{ github.sha }}'
      - if: ${{ endsWith(github.event.number, '9') || endsWith(github.sha, 'f') }}
        run: |
          set -x
          go test -v ./... -race
          go test    ./... -count=10000
