on:
  workflow_call:
    inputs:
      prefix:
        type: string
      runs-on:
        required: true
        type: string
      run:
        type: string
    outputs:
      modules:
        value: ${{ jobs.resolve-modules.outputs.modules }}

jobs:
  resolve-modules:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      modules: ${{ steps.resolve.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - id: resolve
        run: |
          modules="$(find -name go.mod -type f -printf '"%h", ')"
          echo "modules=[${modules%??}]" >> $GITHUB_OUTPUT

  module:
    if: inputs.prefix || inputs.run
    needs: resolve-modules
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.resolve-modules.outputs.modules) }}
    name: '${{ inputs.prefix }}-module (${{ matrix.module }})'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - working-directory: ${{ matrix.module }}
        run: ${{ inputs.run }}
